version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:qwerty@db:5433/
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  db_data:
