"""add role in profile

Revision ID: 09a76cd4cd15
Revises: badd67f2f212
Create Date: 2024-12-30 23:40:22.466865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09a76cd4cd15"
down_revision: Union[str, None] = "badd67f2f212"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("role_profile_id_fkey", "role", type_="foreignkey")
    op.drop_column("role", "profile_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role",
        sa.Column(
            "profile_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "role_profile_id_fkey", "role", "profile", ["profile_id"], ["id"]
    )
    # ### end Alembic commands ###
