"""change test table

Revision ID: 374ed29cc88f
Revises: f35de246b14f
Create Date: 2025-01-08 01:59:24.196593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "374ed29cc88f"
down_revision: Union[str, None] = "f35de246b14f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test", sa.Column("creator_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("test_teacher_id_fkey", "test", type_="foreignkey")
    op.create_foreign_key(None, "test", "profile", ["creator_id"], ["id"])
    op.drop_column("test", "teacher_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test",
        sa.Column(
            "teacher_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "test", type_="foreignkey")
    op.create_foreign_key(
        "test_teacher_id_fkey", "test", "profile", ["teacher_id"], ["id"]
    )
    op.drop_column("test", "creator_id")
    # ### end Alembic commands ###
