"""Change links CourseStudentAssociation

Revision ID: bf492ac1d6e5
Revises: d8d2214f1a99
Create Date: 2025-01-06 02:19:35.827835

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf492ac1d6e5"
down_revision: Union[str, None] = "d8d2214f1a99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_student_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("coursestudentassociation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coursestudentassociation",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "course_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "profile_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name="coursestudentassociation_course_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
            name="coursestudentassociation_profile_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="coursestudentassociation_pkey"),
    )
    op.drop_table("course_student_association")
    # ### end Alembic commands ###
