"""Database creation

Revision ID: 538c7f02a3fa
Revises: 200a898f0c9f
Create Date: 2025-01-12 15:37:49.690022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "538c7f02a3fa"
down_revision: Union[str, None] = "200a898f0c9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_progress", sa.Column("attempt_date", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_progress", "attempt_date")
    # ### end Alembic commands ###
