"""фÐadd percent

Revision ID: 4aca4661f4ff
Revises: 75cc277e026f
Create Date: 2025-01-12 16:42:49.998739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4aca4661f4ff"
down_revision: Union[str, None] = "75cc277e026f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_progress", sa.Column("percent", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_progress", "percent")
    # ### end Alembic commands ###
