"""сÐcreate test_progress

Revision ID: 012074672316
Revises: 1660d43fd0db
Create Date: 2025-01-12 13:59:46.208666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "012074672316"
down_revision: Union[str, None] = "1660d43fd0db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_progress", "correct_answer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_progress",
        sa.Column(
            "correct_answer", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
