"""фÐadd count

Revision ID: aca00fdae1ef
Revises: 4aca4661f4ff
Create Date: 2025-01-12 16:44:17.130461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aca00fdae1ef"
down_revision: Union[str, None] = "4aca4661f4ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_progress",
        sa.Column("count_current_answer", sa.Integer(), nullable=True),
    )
    op.drop_column("test_progress", "percent")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_progress",
        sa.Column("percent", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("test_progress", "count_current_answer")
    # ### end Alembic commands ###
