"""сÐcreate test_progress

Revision ID: 23f00adc340f
Revises: 8916e5c45432
Create Date: 2025-01-11 22:08:29.634879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23f00adc340f"
down_revision: Union[str, None] = "8916e5c45432"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_progress_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text_question", sa.String(), nullable=False),
        sa.Column("options", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("correct_answer", sa.String(), nullable=False),
        sa.Column("student_answer", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "testprogress",
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("count_question", sa.Integer(), nullable=True),
        sa.Column("correct_answer", sa.Integer(), nullable=True),
        sa.Column("deadline_date", sa.DateTime(), nullable=True),
        sa.Column("timelimit", sa.Interval(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testprogress")
    op.drop_table("test_progress_result")
    # ### end Alembic commands ###
