"""change test

Revision ID: f35de246b14f
Revises: 64a7144fa8ba
Create Date: 2025-01-07 19:13:53.135994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f35de246b14f"
down_revision: Union[str, None] = "64a7144fa8ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test", sa.Column("teacher_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "test", "profile", ["teacher_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "test", type_="foreignkey")
    op.drop_column("test", "teacher_id")
    # ### end Alembic commands ###
